/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "onnx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(onnx_AttributeProto, onnx_AttributeProto, 2)


PB_BIND(onnx_ValueInfoProto, onnx_ValueInfoProto, AUTO)


PB_BIND(onnx_NodeProto, onnx_NodeProto, AUTO)


PB_BIND(onnx_TrainingInfoProto, onnx_TrainingInfoProto, AUTO)


PB_BIND(onnx_ModelProto, onnx_ModelProto, AUTO)


PB_BIND(onnx_StringStringEntryProto, onnx_StringStringEntryProto, AUTO)


PB_BIND(onnx_TensorAnnotation, onnx_TensorAnnotation, AUTO)


PB_BIND(onnx_GraphProto, onnx_GraphProto, AUTO)


PB_BIND(onnx_TensorProto, onnx_TensorProto, AUTO)


PB_BIND(onnx_TensorProto_Segment, onnx_TensorProto_Segment, AUTO)


PB_BIND(onnx_SparseTensorProto, onnx_SparseTensorProto, AUTO)


PB_BIND(onnx_TensorShapeProto, onnx_TensorShapeProto, AUTO)


PB_BIND(onnx_TensorShapeProto_Dimension, onnx_TensorShapeProto_Dimension, AUTO)


PB_BIND(onnx_TypeProto, onnx_TypeProto, AUTO)


PB_BIND(onnx_TypeProto_Tensor, onnx_TypeProto_Tensor, AUTO)


PB_BIND(onnx_TypeProto_Sequence, onnx_TypeProto_Sequence, AUTO)


PB_BIND(onnx_TypeProto_Map, onnx_TypeProto_Map, AUTO)


PB_BIND(onnx_TypeProto_Optional, onnx_TypeProto_Optional, AUTO)


PB_BIND(onnx_TypeProto_SparseTensor, onnx_TypeProto_SparseTensor, AUTO)


PB_BIND(onnx_OperatorSetIdProto, onnx_OperatorSetIdProto, AUTO)


PB_BIND(onnx_FunctionProto, onnx_FunctionProto, AUTO)








#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

